/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package record;

import java.awt.Color;
import javax.swing.ImageIcon;
import login.*;
import rsscalelabel.RSScaleLabel;

/**
 *
 * @author Usuario
 */
public class frmRecord extends javax.swing.JFrame {

    private String nickname;
    /**
     * Creates new form frmRecord
     */
    public frmRecord() {
        initComponents();
        designframe();        
    }
    
    public frmRecord(String nickname) {
        initComponents();
        designframe();
        this.nickname = nickname;
        openfiles();
    }
    
    public void designframe(){
        getContentPane().setBackground(new Color(5, 111, 148));
        //setIconImage(new ImageIcon(getClass().getResource("/images/logo.png")).getImage());
        setIconImage(new ImageIcon("images/logo1.png").getImage());
        RSScaleLabel.setScaleLabel(jlbllogo, "./images/umg.png");
    }
    
    public void openfiles(){
        // Creamos una instancia de ClsOpenFile pasándole el JTextField
        clsOpenFiles openFile = new clsOpenFiles(jtxarecord, this);

        // Llamamos al método para abrir el archivo
        openFile.abrirArchivoEspecifico("./records/record.csv");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxarecord = new javax.swing.JTextArea();
        jbtnreturn = new javax.swing.JButton();
        jlbllogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 450));
        setMinimumSize(new java.awt.Dimension(580, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(580, 450));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial");

        jtxarecord.setBackground(new java.awt.Color(3, 115, 120));
        jtxarecord.setColumns(20);
        jtxarecord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxarecord.setForeground(new java.awt.Color(255, 255, 255));
        jtxarecord.setRows(5);
        jtxarecord.setEnabled(false);
        jScrollPane1.setViewportView(jtxarecord);

        jbtnreturn.setBackground(new java.awt.Color(0, 51, 102));
        jbtnreturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnreturn.setForeground(new java.awt.Color(255, 255, 255));
        jbtnreturn.setText("Regresar");
        jbtnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnreturnActionPerformed(evt);
            }
        });

        jlbllogo.setText("Logo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jbtnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreturnActionPerformed
        // TODO add your handling code here:
        frmMenu frmmenu = new frmMenu(nickname);
        frmmenu.setLocationRelativeTo(null);
        frmmenu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jbtnreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnreturn;
    private javax.swing.JLabel jlbllogo;
    private javax.swing.JTextArea jtxarecord;
    // End of variables declaration//GEN-END:variables
}
